### ISSUE TITLE
How to participate in HOWL Beta

### ISSUE THREAD

**Issue by AceGodsLuv** [howlsocial/howldocs#5]
✨HOWL Beta is now out✨

👾Full info & challenges can be found: https://docs.howl.social/blog
Testnet claim/airdrop checker: https://testnet-claim.howl.social
Beta site: https://beta.howl.social

🪄To get going on beta:
1. Get JUNOX (if you don't have any, go to the Juno discord at https://discord.gg/Juno, and request them in the #faucet channel)
2. Claim beta airdrop https://testnet-claim.howl.social
3. Go to beta site https://beta.howl.social

**Comment by the-frey** [comment]
Please don't open issues on the docs GitHub unless there is an actual issue. The docs tasks that still are unclaimed are listed on the docs page and need to be added to the documentation, not as GitHub issues. Thanks
